# Build Stage
FROM node:20-alpine AS builder
WORKDIR /usr/src/app/server
COPY server/package*.json ./
RUN npm ci --only=production
COPY server/ ./

# Production Stage
FROM node:20-alpine
WORKDIR /usr/src/app/server
COPY --from=builder /usr/src/app/server ./
EXPOSE 55555
CMD ["npm", "start"]
