sonar.projectKey=jonas3688_projetoIndividualGCES-2026.1
sonar.organization=jonas3688
sonar.sources=server,game/src
sonar.exclusions=**/node_modules/**,**/test/**
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
